version: "3.9"
services:
  app:
    image: registry.digitalocean.com/opentag-ms/opentag-ms-backend
    platform: linux/amd64
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      - ./opentag.sqlite:/usr/src/app/opentag.sqlite
