version: "3.9"
services:
  app:
    image: registry.digitalocean.com/registry.digitalocean.com/opentag-ms/opentag-ms-backend
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./opentag.sqlite:/usr/src/app/opentag.sqlite
